version: "3.1"

services:
  local-mysql:
    image: mysql:8.0.34
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - local-mysql
    restart: unless-stopped
    ports:
      - "8081:80"
    env_file: .env
    environment:
      PMA_HOST: local-mysql
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - spring-network

  adqualtech-school:
    image: adqualtech-school
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - local-mysql
    env_file: .env
    ports:
      - "8080:8080"
    environment:
      DOCKER_USERNAME: '${DOCKERHUB_USERNAME}'
      DOCKER_TOKEN: '${DOCKERHUB_TOKEN}'
      SPRING_DATASOURCE_URL: '${SPRING_DATASOURCE_URL}'
      SPRING_DATASOURCE_USERNAME: '${MYSQL_USER}'
      SPRING_DATASOURCE_PASSWORD: '${MYSQL_PASSWORD}'
    networks:
      - spring-network
    volumes:
      - type: bind
        source: '${STATIC_DIR}'
        target: /static

volumes:
  db-data:

networks:
  spring-network:
    driver: bridge