package com.management.adqualtechschool.common;

public interface DisplayTypeAndFilterAndPaginationType {
    String LIST = "list";
    String FILTER = "filter";
    String SEARCH = "search";
    String TYPE = "type";
    String TODAY = "Hôm nay";
    String YESTERDAY = "Hôm qua";
    String WEEK_AGO = "1 tuần gần đây";
    String MONTH_AGO = "1 tháng gần đây";
    String YEAR_AGO = "1 năm gần đây";
    String CREATOR = "Người tạo";
    String SCOPE = "Phạm vi";
    String SCHOOL_WIDE = "Toàn trường";
    String SCOPE_LIST = "scopeList";
    String ACCOUNT_LIST = "accountList";
    String CREATED_AT = "createdAt";
    String UPDATED_AT = "updatedAt";
    String START_AT = "startAt";
    String END_AT = "endAt";
    String CURRENT_PAGE = "currentPage";
    String PAGE_NUMBERS = "pageNumbers";
    String CREATOR_NAME= "creatorName";
    String SCOPE_NAME = "scopeName";
    String SUBJECT_LIST = "subjectList";
    String SUBJECT = "Môn";
    String SUBJECT_NAME = "subjectName";
    String CLASS_NAME_DEFAULT = "Lớp";
    String GRADE_NAME_DEFAULT = "Khối";
    String TEACHER = "teacher";
    String TEACHER_INFO = "teacherInfo";
    String PUPIL_INFO = "pupilInfo";
    String PUPIL_ACCOUNT = "pupil";
    String GRADE_LIST = "gradeList";
    String CLASS_LIST = "classList";
    String GRADE_NAME = "gradeName";
    String CLASS_NAME = "className";
    String TEACHER_LIST = "teacherList";
    String STUDY_ROOM_LIST = "studyRoomList";
    String TIMETABLE_REQUIRE_LIST = "timetableRequireList";
    String TIMETABLE = "timetable";
}
